### ISSUE TITLE
Setting active profile

### ISSUE THREAD

**Issue by DavidCrandall-charter** [Samsung/vscode-extension-tizentv#21]
I'm sure this is solved, but I keep getting

`Build Package (Build failed: no active profile!)`

And I don't see where I set the active profile.  I've definitely created a certificate at least 2-3 times.

**Comment by DavidCrandall-charter** [comment]
Before going too far, also set witsconfig profile name here 

https://github.com/Samsung/Wits/wiki/Set-Wits-Environment#data-structure-of-witsconfigjson

**Comment by prozanne** [comment]
Hi, Sorry for inconvenience.
https://samsung.github.io/vscode-extension-tizentv

You can set active profile at "Tizen TV: Run Certificate Manager" command.
1. Press F1 to open the command palette.
2. Type "Tizen TV: Run Certificate Manager"
3. Select "set Active Profile" (At least once, you have to run "Craete Profile (Tizen)")
4. After seeing the success notification at the right-bottom, you can run "Tizen TV: Build Signed Package" to build your application.

Thanks.
