### ISSUE TITLE
Deploy Extension fails with error

### ISSUE THREAD

**Issue by prate3k** [Samsung/vscode-extension-tizentv#39]
It seems the personal access token used for deploying extension is expired, as per logs here : https://github.com/Samsung/vscode-extension-tizentv/runs/5458334156?check_suite_focus=true

Please check.

@taronlee @SejoongDeJang @pwsses

**Comment by pwsses** [comment]
Hello.
You are right. We will check it. 
Thank you.

**Comment by prate3k** [comment]
No worries. I'm just excited for the new changes to rollout. :) 

Please update once done.

**Comment by prate3k** [comment]
Team, any update here?

@pwsses @taronlee @SejoongDeJang

**Comment by SejoongDeJang** [comment]
@prate3k Succeed releasing to `v1.2.6`.

![image](https://user-images.githubusercontent.com/24784445/157619647-8f2f5304-f7e9-4e0b-9464-8aac01d86239.png)
Thanks @prate3k
