### ISSUE TITLE
How to use the RTL simulator for TV devices

### ISSUE THREAD

**Issue by Shaharbad** [Samsung/vscode-extension-tizentv#63]
Could anyone provide a detailed guide or steps on how to properly upload and test a Tizen app using the RTL simulator for TV devices?

It's not clear on the website

**Comment by prozanne** [comment]
Hi, which step are you stuck in?
Can you see the TV screen via RTL? (You have to assign a new device from the site)
Are you in trouble to launch your application to RTL TV through the tizentv extension?

**Comment by Shaharbad** [comment]
> Hi, which step are you stuck in? Can you see the TV screen via RTL? (You have to assign a new device from the site) Are you in trouble to launch your application to RTL TV through the tizentv extension?

I can see the tv on my browser, just wondering how to launch my application from the IDE to the TV.
Please provide a step by step tutorial

**Comment by prozanne** [comment]
Hi,
Did you check this guide?
Could you please try to follow this step first?
https://github.com/Samsung/vscode-extension-tizentv/wiki/Setting-for-%22RTL-TV%22-in-%22Tizentv-extension%22

**Comment by Shaharbad** [comment]
> Hi, Did you check this guide? Could you please try to follow this step first? https://github.com/Samsung/vscode-extension-tizentv/wiki/Setting-for-%22RTL-TV%22-in-%22Tizentv-extension%22

Thank you, I'll check it out and if I still have a problem I will contact you.
